const policy = [
  {
    title: 'Interpretation and Definitions',
    text: 'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
    sections: [],
  },
  {
    title: 'Definitions',
    text: '',
    sections: [
      {
        subTitle: '',
        heading: '',
        children: [
          {
            text: 'For the purposes of this Privacy Policy:',
            bulletPoints: [
              'Account means a unique account created for You to access our Service or parts of our Service.',
              'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
              'Application means the software program provided by the Company downloaded by You on any electronic device, named Luxim.',
              'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to LuximApp Limited, 32-34 Opebi Road, Ikeja, Lagos, Nigeria.',
              'Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
              'Country refers to: Nigeria.',
              'Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.',
              'Personal Data is any information that relates to an identified or identifiable individual.',
              'Service refers to the Application or the Website or both.',
              'Service Provider means any natural or legal person who processes the data.',
              'On behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analysing how the Service is used.',
              'Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.',
              'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
              'Website refers to Luxim, accessible from <a href="https://www.luximapp.com/" style="font-weight: 800" target="_blank"> www.luximapp.com.</a>',
              'You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'Collecting and Using Your Personal Data',
    text: '',
    sections: [
      {
        subTitle: 'Types of Data Collected',
        heading: 'Personal Data:',
        children: [
          {
            text: 'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
            bulletPoints: [
              'Email address',
              'First name and last name',
              'Phone number',
              'Address, State, Province, ZIP/Postal code, City',
              'Bank account information in order to pay for products and/or services within',
              'The Service',
              'Usage Data',
            ],
          },
          {
            text: 'When You pay for a product and/or a service via bank transfer, We may ask You to provide information to facilitate this transaction and to verify Your identity. Such information may include, without limitation:',
            bulletPoints: [
              'Date of birth',
              'Passport or National ID card',
              'Bank card statemen',
              'Other information linking You to an address',
            ],
          },
        ],
      },
      {
        subTitle: 'Usage Data',
        heading: '',
        children: [
          {
            text: "Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
            bulletPoints: [],
          },
          {
            text: `When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.`,
            bulletPoints: [],
          },
        ],
      },
      {
        subTitle: 'Information from Third-Party Social Media Services',
        heading: '',
        children: [
          {
            text: 'The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:',
            bulletPoints: ['Apple', 'Google', 'Facebook', 'Twitter'],
          },
          {
            text: "If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.",
            bulletPoints: [],
          },
          {
            text: "You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy",
            bulletPoints: [],
          },
        ],
      },
      {
        subTitle: 'Information Collected while Using the Application',
        heading: '',
        children: [
          {
            text: 'While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:',
            bulletPoints: [
              'Information regarding your location',
              "Information from your Device's phone book (contacts list)",
              "Pictures and other information from your Device's camera and photo library",
            ],
          },
          {
            text: `We use this information to provide features of Our Service, to improve and customise Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
            You can enable or disable access to this information at any time, through Your Device settings.`,
            bulletPoints: [],
          },
        ],
      },
      {
        subTitle: 'Tracking Technologies and Cookies',
        heading: '',
        children: [
          {
            text: "We use this information to provide features of Our Service, to improve and customise Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device. You can enable or disable access to this information at any time, through Your Device settings.",
            bulletPoints: [
              'Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies. ',
              'Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read "Where can I change the settings for disabling, or deleting local shared objects?" available <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local _shared_objects_" target="_blank">here</a>',
              'Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).',
            ],
          },
          {
            text: 'Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies: Cookies by PrivacyPolicies Generator.',
            bulletPoints: [],
          },
          {
            text: 'We use both Session and Persistent Cookies for the purposes set out below:',
            bulletPoints: [
              'Necessary / Essential Cookies Type: Session Cookies Administered by: Us Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.',
              ' Cookies Policy / Notice Acceptance Cookies Type: Persistent Cookies Administered by: Us',
              'Purpose: These Cookies identify if users have accepted the use of cookies on the Website.',
              'Functionality Cookies Type: Persistent Cookies Administered by: Us Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.',
              'Tracking and Performance Cookies Type: Persistent Cookies Administered by: Third-Parties Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them.',
            ],
          },
          {
            text: 'For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.',
            bulletPoints: [],
          },
        ],
      },
    ],
  },
  {
    title: 'Use of Your Personal Data',
    text: '',
    sections: [
      {
        subTitle: '',
        heading: '',
        children: [
          {
            text: 'The Company may use Personal Data for the following purposes:',
            bulletPoints: [
              'To provide and maintain our Service, including to monitor the usage of our Service.',
              'To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.',
              'For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.',
              "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
              'To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.',
              'To manage Your requests: To attend and manage Your requests to Us.',
              'To deliver targeted advertising to You: We may use Your information to develop and display content and advertising (and work with third-party vendors who do so) tailored to Your interests and/or location and to measure its effectiveness.',
              'For business transfers: We may use Your information to evaluate or conduct merger, divestiture, restructuring, reorganisation, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.',
              'For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.',
            ],
          },
          {
            text: 'We may share Your personal information in the following situations:',
            bulletPoints: [
              'With Service Providers: We may share Your personal information with Service Providers to monitor and analyse the use of our Service, to advertise on third party websites to You after You visited our Service, for payment processing, to contact You.',
              'For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.',
              'With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honour this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.',
              'With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.',
              'With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.',
              'With Your consent: We may disclose Your personal information for any other purpose with Your consent.',
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'Retention of Your Personal Data',
    text: `The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to
    strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.`,
    sections: [],
  },
  {
    title: 'Transfer of Your Personal Data',
    text: `Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
    Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
    The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of Your data and other personal information.`,
    sections: [],
  },
  {
    title: 'Disclosure of Your Personal Data',
    sections: [
      {
        subTitle: '',
        heading: '',
        children: [
          {
            text: 'Business Transactions',
            bulletPoints: [],
          },
          {
            text: 'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.',
            bulletPoints: [],
          },
          {
            text: 'Law enforcement',
            bulletPoints: [],
          },
          {
            text: 'Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency)',
            bulletPoints: [],
          },
          {
            text: 'Other legal requirements',
            bulletPoints: [],
          },
          {
            text: 'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:',
            bulletPoints: [
              'Comply with a legal obligation',
              'Protect and defend the rights or property of the Company',
              'Prevent or investigate possible wrongdoing in connection with the Service',
              'Protect the personal safety of Users of the Service or the public',
              'Protect against legal liability',
            ],
          },
        ],
      },
    ],
    text: '',
  },
  {
    title: 'Security of Your Personal Data',
    text: 'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.',
    sections: [],
  },
  {
    title: 'Detailed Information on the Processing of Your Personal Data',
    text: 'The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.',
    sections: [],
  },
  {
    title: 'Analytics',
    sections: [
      {
        subTitle: '',
        heading: '',
        children: [
          {
            text: 'We may use third-party Service providers to monitor and analyze the use of our Service.',
            bulletPoints: [],
          },
          {
            text: '',
            bulletPoints: [
              '<span style="font-weight: 800">Google Analytics: </span>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network. You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity. You may opt-out of certain Google Analytics features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy <a href="https://policies.google.com/privacy" target="_blank">(here)</a> For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy" target="_blank">(here)</a>',
              '<span style="font-weight: 800">Firebase Firebase: </span> is an analytics service provided by Google Inc. You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy <a href="https://policies.google.com/privacy" target="_blank">(here)</a> We also encourage you to review the Google\'s policy for safeguarding your data <a href="https://support.google.com/analytics/answer/6004245" target="_blank">(here)</a>. For more information on what type of information Firebase collects, please visit the How Google uses data when you use our partners\' sites or apps webpage <a href="https://policies.google.com/technologies/partner-sites" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">Matomo Matomo: </span> is a web analytics service. You can visit their Privacy Policy page <a href="https://matomo.org/privacy-policy" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">Clicky Clicky:</span> is a web analytics service. Read the Privacy Policy for Clicky <a href="https://clicky.com/terms" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">Statcounter Statcounter:</span> is a web traffic analysis tool. You can read the Privacy Policy for Statcounter <a href="https://statcounter.com/about/legal/" target="_blank">(here)</a>',
              '<span style="font-weight: 800">Flurry Analytics:</span> Flurry Analytics service is provided by Yahoo! Inc. You can opt-out from Flurry Analytics service to prevent Flurry Analytics from using and sharing your information by visiting the Flurry\'s Opt-out page <a href="https://developer.yahoo.com/flurry/end-user-opt-out/" target="_blank">(here)</a>. For more information on the privacy practices and policies of Yahoo!, please visit their Privacy Policy page <a href="https://policies.yahoo.com/xa/en/yahoo/privacy/index.htm" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">Mixpanel Mixpanel:</span> is provided by Mixpanel Inc. You can prevent Mixpanel from using your information for analytics purposes by opting-out. To opt-out of Mixpanel service, please visit this page <a href="https://mixpanel.com/optout/" target="_blank">(here)</a>. For more information on what type of information Mixpanel collects, please visit the Terms of Use page of Mixpanel <a href="https://mixpanel.com/terms/"target="_blank">(here)</a>',
              '<span style="font-weight: 800">Unity Analytics:</span> Unity Analytics is provided by Unity Technologies. Unity Analytics collects, stores, uses, processes, and transfers personal information to provide, operate, and improve Unity Technologies services, including personalized advertising services. For more information on what type of information Unity Technologies collects, please visit their Privacy Policy page <a href="https://unity3d.com/legal/privacy-policy" target="_blank">(here)</a>. You can prevent Unity Analytics from using your information by opting-out. To opt-out of Unity Analytics, please visit this page <a href="https://unity3d.com/legal/privacy-policy" target="_blank">(here)</a> You may opt-out of all personalized advertising by enabling privacy features on Your mobile device such as Limit Ad Tracking (iOS) and Opt Out of Ads Personalization (Android). See Your mobile device Help system for more information.',
            ],
          },
        ],
      },
    ],
    text: '',
  },
  {
    title: 'Email Marketing',
    sections: [
      {
        subTitle: '',
        heading: '',
        children: [
          {
            text: 'We may use third-party Service providers to monitor and analyze the use of our Service.',
            bulletPoints: [],
          },
          {
            text: `We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.
                We may use Email Marketing Service Providers to manage and send emails to You.`,
            bulletPoints: [
              '<span style="font-weight: 800">Mailchimp Mailchimp:</span> is an email marketing sending service provided by The Rocket Science Group LLC. For more information on the privacy practices of Mailchimp, please visit their Privacy policy <a href="https://mailchimp.com/legal/privacy" target="_blank">(here)</a>',
              '<span style="font-weight: 800">AWeber AWeber:</span> is an email marketing sending service provided by AWeber Communications. For more information on the privacy practices of AWeber, please visit their Privacy policy <a href="https://www.aweber.com/privacy.htm" target="_blank">(here)</a>',
              '<span style="font-weight: 800">GetResponse:</span> GetResponse is an email marketing sending service provided by GetResponse. For more information on the privacy practices of GetResponse, please visit their Privacy policy <a href="https://www.getresponse.com/legal/privacy.html" target="_blank">(here)</a>',
            ],
          },
        ],
      },
    ],
    text: '',
  },
  {
    title: 'Payments',
    sections: [
      {
        subTitle: '',
        heading: '',
        children: [
          {
            text: `We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).
            We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.`,
            bulletPoints: [
              '<span style="font-weight: 800">Apple Store In-App Payments:</span> Their Privacy Policy can be viewed <a href="https://www.apple.com/legal/privacy/en-ww/" target="_blank">(here)</a>',
              '<span style="font-weight: 800">Google Play In-App Payments:</span> Their Privacy Policy can be viewed <a href="https://www.google.com/policies/privacy/" target="_blank">(here)</a>',
              '<span style="font-weight: 800">PayPal: </span> Their Privacy Policy can be viewed <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full/" target="_blank">(here)</a>',
              '<span style="font-weight: 800">Paystack:</span> Their Privacy Policy can be viewed <a href="https://paystack.com/privacy/merchant#:~:text=Paystack%20does%20not%20sell%2C%20trade,described%20in%20this%20Privacy%20Policy" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">Flutterwave:</span> Their Privacy Policy can be viewed <a href="https://flutterwave.com/us/privacy-policy" target="_blank">(here)</a>',
              'When You use Our Service to pay a product and/or service via bank transfer, We may ask You to provide information to facilitate this transaction and to verify Your identity.',
            ],
          },
        ],
      },
    ],
    text: '',
  },
  {
    title: 'Behavioral Remarketing',
    sections: [
      {
        subTitle: '',
        heading: '',
        children: [
          {
            text: `The Company uses remarketing services to advertise to You after You accessed or visited our Service. We and Our third-party vendors use cookies and non-cookie technologies to help Us recognize Your Device and understand how You use our Service so that We can improve our Service to reflect Your interests and serve You advertisements that are likely to be of more interest to You.
            These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies and to enable Us to:`,
            bulletPoints: [
              'Measure and analyse traffic and browsing activity on Our Service ',
              'Show advertisements for our products and/or services to You on third-party websites or apps',
              'Measure and analyse the performance of Our advertising campaigns',
            ],
          },
          {
            text: 'Some of these third-party vendors may use non-cookie technologies that may not be impacted by browser settings that block cookies. Your browser may not permit You to block such technologies. You can use the following third-party tools to decline the collection and use of information for the purpose of serving You interest-based advertising:',
            bulletPoints: [
              'The NAI\'s opt-out platform <a href="http://www.networkadvertising.org/choices/" target="_blank">(here)</a>  ',
              'The EDAA\'s opt-out platform <a href="http://www.youronlinechoices.com/" target="_blank">(here)</a>',
              'The DAA\'s opt-out platform <a href="http://optout.aboutads.info/?c=2&lang=EN" target="_blank">(here)</a>',
            ],
          },
          {
            text: `You may opt-out of all personalised advertising by enabling privacy features on Your mobile device such as Limit Ad Tracking (iOS) and Opt Out of Ads Personalisation (Android). See Your mobile device Help system for more information.
            We may share information, such as hashed email addresses (if available) or other online identifiers collected on Our Service with these third-party vendors. This allows Our third-party vendors to recognise and deliver You ads across devices and browsers. To read more about the technologies used by these third-party vendors and their cross-device capabilities please refer to the Privacy Policy of each vendor listed below.`,
            bulletPoints: [],
          },
          {
            text: 'The third-party vendors We use are:',
            bulletPoints: [
              '<span style="font-weight: 800">Google Ads (AdWords):</span> Google Ads (AdWords) remarking service is provided by Google Inc. You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the Google Ads Settings page <a href="http://www.google.com/settings/adsGoogle" target="_blank">(here)</a> also recommends installing the Google Analytics Opt-out Browser Add-on - <a href="https://tools.google.com/dlpage/gaoptout" target="_blank">(here)</a>  - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics. For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page <a href="https://policies.google.com/privacy" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">Bing Ads Remarketing:</span> Bing Ads remarketing service is provided by Microsoft Inc. You can opt-out of Bing Ads interest-based ads by following their instructions <a href="https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized" target="_blank">(here)</a> -ads You can learn more about the privacy practices and policies of Microsoft by visiting their Privacy Policy page <a href="https://privacy.microsoft.com/en-us/PrivacyStatement" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">Twitter:</span> Twitter remarketing service is provided by Twitter Inc. You can opt-out from Twitter\'s interest-based ads by following their instructions <a href="https://support.twitter.com/articles/20170405" target="_blank">(here)</a> You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page <a href="https://twitter.com/privacy" target="_blank">(here)</a> ',
              '<span style="font-weight: 800">Facebook: </span>Facebook remarketing service is provided by Facebook Inc. You can learn more about interest-based advertising from Facebook by visiting this page <a href="https://www.facebook.com/help/516147308587266 " target="_blank">(here)</a>. To opt-out from Facebook\'s interest-based ads, follow these instructions from Facebook <a href="https://www.facebook.com/help/568137493302217" target="_blank">(here)</a>. Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA <a href="http://www.aboutads.info/choices/" target="_blank">(here)</a>, the Digital Advertising Alliance of Canada in Canada <a href="http://youradchoices.ca/" target="_blank">(here)</a> or the European Interactive Digital Advertising Alliance in Europe <a href="http://www.youronlinechoices.eu/" target="_blank">(here)</a>, or opt-out using your mobile device settings. For more information on the privacy practices of Facebook, please visit Facebook\'s Data Policy <a href="https://www.facebook.com/privacy/explanation" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">Pinterest:</span> Pinterest remarketing service is provided by Pinterest Inc. You can opt-out from Pinterest\'s interest-based ads by enabling the "Do Not Track" functionality of your web browser or by following Pinterest instructions <a href="http://help.pinterest.com/en/articles/personalization-and-data" target="_blank">(here)</a>. You can learn more about the privacy practices and policies of Pinterest by visiting their Privacy Policy page <a href="https://about.pinterest.com/en/privacy-policy" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">AdRoll:</span> AdRoll remarketing service is provided by NextRoll, Inc. You can opt-out of AdRoll remarketing by visiting this AdRoll Advertising Preferences web page <a href="http://info.evidon.com/pub_info/573?v=1&nt=1&nw=false" target="_blank">(here)</a> or the Opt Out of Personalized Advertising web page <a href="https://help.adroll.com/hc/en-us/articles/216599538-Opting-Out-of-Personalized-Advertising" target="_blank">(here)</a> . If You are a California resident, please read the "Information For California Residents Only" section in the Privacy Policy of NextRoll, Inc. <a href="https://www.nextroll.com/privacy#service-13" target="_blank">(here)</a>. For more information on the privacy practices of AdRoll, please visit the NextRoll, Inc. Privacy Policy web page <a href="https://www.nextroll.com/privacy" target="_blank">(here)</a>.',
              '<span style="font-weight: 800">Perfect Audience:</span> Perfect Audience remarketing service is provided by NowSpots Inc. You can opt-out of Perfect Audience remarketing by visiting these pages: Platform Opt-out <a href="http://pixel.prfct.co/coo" target="_blank">(here)</a>. and Partner Opt-out <a href="hhttp://ib.adnxs.com/optout" target="_blank">(here)</a>. For more information on the privacy practices of Perfect Audience, please visit the Perfect Audience Privacy Policy & Opt-out web page <a href="https://www.perfectaudience.com/privacy/" target="_blank">(here)</a>',
              '<span style="font-weight: 800">AppNexus</span> AppNexus remarketing service is provided by AppNexus Inc. You can opt-out of AppNexus remarketing by visiting the Privacy & the AppNexus Platform web page <a href="https://www.appnexus.com/platform-privacy-policy" target="_blank">(here)</a> For more information on the privacy practices of AppNexus, please visit the AppNexus Platform Privacy Policy web page <a href="https://www.appnexus.com/platform-privacy-policy" target="_blank">(here)</a>',
            ],
          },
        ],
      },
    ],
    text: '',
  },
  {
    title: 'Usage, Performance and Miscellaneous',
    sections: [
      {
        subTitle: '',
        heading: '',
        children: [
          {
            text: 'We may use third-party Service Providers to provide better improvement of our Service.',
            bulletPoints: [
              '<span style="font-weight: 800">Invisible reCAPTCHA: </span>We use an invisible captcha service named reCAPTCHA. reCAPTCHA is operated by Google. The reCAPTCHA service may collect information from You and from Your Device for security purposes. The information gathered by reCAPTCHA is held in accordance with the Privacy Policy of Google <a href="https://www.google.com/intl/en/policies/privacy/" target="_blank">(here)</a>',
              'Mouseflow: Mouseflow is a session replay and heatmap tool that shows how visitors click, move, scroll, browse, and pay attention on websites. The service is operated by ApS. Mouseflow service may collect information from Your device. The information gathered by Mouseflow is held in accordance with its Privacy Policy <a href="https://mouseflow.com/privacy/" target="_blank">(here)</a>',
              '<span style="font-weight: 800">FreshDesk: </span> FreshDesk is a customer support software. The service is operated by Freshworks, Inc. FreshDesk service may collect information from Your Device. The information gathered by FreshDesk is held in accordance with its Privacy Policy <a href="https://www.freshworks.com/privacy/">(here)</a>',
              '<span style="font-weight: 800">Google Places: </span>Google Places is a service that returns information about places using HTTP requests. It is operated by Google Google Places service may collect information from You and from Your Device for security purposes. The information gathered by Google Places is held in accordance with the Privacy Policy of Google <a href="https://www.google.com/intl/en/policies/privacy/">(here)</a>',
              '<span style="font-weight: 800">Twilio </span> Their Privacy Policy can be viewed <a href="https://www.twilio.com/legal/privacy">(here)</a>',
            ],
          },
        ],
      },
    ],
    text: '',
  },
  {
    title: "Children's Privacy",
    text: `Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
    If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.`,
    sections: [],
  },
  {
    title: 'Links to Other Websites',
    text: `Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.`,
    sections: [],
  },
  {
    title: 'Changes to this Privacy Policy',
    text: `We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.`,
    sections: [],
  },
  {
    title: 'Contact Us',
    text: 'If you have any questions about this Privacy Policy, You can contact us by email: <a href="mailto:hello@luximapp.com" style="font-weight: 800">support@luximapp.com</a>',
    sections: [],
  },
];

export default policy;
